apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: manual-spark-submit
  namespace: workflow-management
  labels:
    app: manual-spark-submit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: manual-spark-submit
  template:
    metadata:
      labels:
        app: manual-spark-submit
    spec:
      containers:
      - name: spark-submit
        image: {{ .Values.charts.airflow.sparkSubmitImage | default "python:3.8-bullseye" | quote }}
        ports:
        - containerPort: 7078
        env:
        - name: JAVA_HOME
          value: /usr/lib/jvm/java-11-openjdk-amd64/
        command: ["/bin/sh"]
        args:
        - -c
        - >-
          apt update &&
          env DEBIAN_FRONTEND=noninteractive apt-get install -y python3-pip ant openjdk-11-jdk &&
          pip3 install --no-input requests==2.28.1 azure==4.0.0 graphframes==0.6 pyspark==3.3.1 &&
          /bin/bash -c -- "while true; do sleep 30; done;"
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
