{{- if .Values.service.enabled -}}
apiVersion: v1beta2
kind: Service
metadata:
  name: {{ .Release.Name }}
  {{- if .Values.environment }}
  labels:
    env: {{ .Values.environment }}
  {{- end }}
spec:
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
{{ end }}
